### PR TITLE
Update AMI

### PR DESCRIPTION
**Pull request by cb372**
to latest ubuntu-wily-java8

### CODE REVIEW

**Comment by LATaylor-guardian** [comment]
You could lower the instance size for this one while you're at it. (It's the only one left on that card after the explorer).

**Comment by LATaylor-guardian** [comment]
:+1:

**Comment by cb372** [comment]
OK, I'll make it t2.nano

**Comment by cb372** [comment]
Note to self: I've updated the stack in CODE, still need to test.

**Comment by cb372** [comment]
Seems stable in CODE after switching from a nano to a micro. I'll update the PROD stack and merge tomorrow.

**Comment by cb372** [comment]
Updated PROD stack.

**Pull request merged**
