### PR TITLE
Improve Bonobo access logging

### PR DESCRIPTION
**Pull request by tomrf1**
1. Enable ELB access logs with CloudFormation
2. Add access logs to the Bonobo app, to provide better details about the user in a separate `audit.log` file.

The format of the new Bonobo log file is e.g.:
```
2016-02-16 17:39:20,056 - tom.forbes@guardian.co.uk GET /
2016-02-16 17:39:25,780 - tom.forbes@guardian.co.uk GET /key/search?query=test
2016-02-16 17:39:28,819 - tom.forbes@guardian.co.uk GET /user/<id>/edit
2016-02-16 17:39:31,852 - tom.forbes@guardian.co.uk POST /user/<id>/edit - Some(Map(csrfToken -> ArrayBuffer(<token>), name -> ArrayBuffer(Chris Test), email -> ArrayBuffer(chris.birchall+testtest@theguardian.com), companyName -> ArrayBuffer(The Guardian - testing), companyUrl -> ArrayBuffer(http://theguardian.com), labelIds -> ArrayBuffer()))
```

### CODE REVIEW

**Comment by mchv** [comment]
As a purely matter of style, you can do this with function composition putting the `audit` method inside the `maybeAuth` function but this is less flexible if you want to limit the audit to some functions not all of them using `maybeAuth`.

**Comment by cb372** [comment]
I agree that we should put this inside the `maybeAuth` method if possible, so that we don't forget to add auditing to any new authenticated endpoints we add in the future.

This requires an understanding of Play's action composition architecture, which can be pretty mindbending... The [docs](https://www.playframework.com/documentation/2.4.x/ScalaActionsComposition) do not really help much. Mariot or I can help with this, although it always confuses me.

**Comment by tomrf1** [comment]
I've updated this to use action composition, so that all request handlers that call `maybeAuth` will always perform auditing. This was...educational.

I still need to look into logging of authorisation failures, so i've added the not-ready-to-merge label.

**Comment by LATaylor-guardian** [comment]
@tomrf1 If you can split the task into two: logging success and logging failure, then do that and it frees this up to be merged then. :)

**Pull request merged**
